$axure.loadCurrentPage({
  "url":"其他人信息.html",
  "generationDate":new Date(1486804101873.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"22ea49dccb32495b844733837ddd334f",
    "type":"Axure:Page",
    "name":"其他人信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4d2967f150dc46348e63af60533b1274",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":1464,
              "y":120},
            "size":{
              "width":409,
              "height":84}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5988c005f8aa4cacb62f5ac9ba02970a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1464,
                  "y":120},
                "size":{
                  "width":409,
                  "height":84}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93f6493fd426410c9776ef676585e533",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":30},
            "size":{
              "width":1334,
              "height":750}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cf20651accd450e899bd97e7410f9bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":30},
                "size":{
                  "width":1334,
                  "height":750}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"65fd10123c8144aca80377f4b52d82eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":148},
            "size":{
              "width":1000,
              "height":515}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4ca6734f54c4b1d8e40b366891c7e30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":187,
                  "y":148},
                "size":{
                  "width":1000,
                  "height":515}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u2.png"}},
{
          "id":"0a3f6c1179c2479e9cce6d9075ce8b08",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":719,
              "y":620},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4793c9a5f9d34484980d9c5cbba1740b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":719,
                  "y":620},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a6cab7211d74f2da131d9385fea1890",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":838,
              "y":620},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dbe31df767b4007bd65b0831dda0063",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":838,
                  "y":620},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"821dbe57ab3c431c827a23f936f6449a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":968,
              "y":620},
            "size":{
              "width":193,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f1b5efd72614362ae3f8ebb899f78c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":968,
                  "y":620},
                "size":{
                  "width":193,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71682685009a476380daa2775c8ec6fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1127,
              "y":138},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c96d895603b74d149a7436d81151813f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1127,
                  "y":138},
                "size":{
                  "width":60,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u26.png"}},
{
          "id":"51a3e67f78b84beb96b6bbf8a542c267",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":293,
              "y":298},
            "size":{
              "width":130,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c4722e86f50447f88ca66981e15c957",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":293,
                  "y":298},
                "size":{
                  "width":130,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u28.png"}},
{
          "id":"af5b6ce8f5a8457e86720203d07c4e4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":448},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"327f1a7b6104479dad3d0c1813ae050d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":448},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40c4ca5325134addb98283b35a171ba6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":486},
            "size":{
              "width":136,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dce0c53f6ac84ed18b474a0a4a67fd22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":486},
                "size":{
                  "width":136,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdbc32624aab4f12a5d51d83ecc9ca79",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":280},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baa576e8da99470abdfbfc761b25c647",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":280},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25ec5397e12849b5b2fcea6dc3324cc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":627,
              "y":280},
            "size":{
              "width":163,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"787ad039a95144eca3bc7821ccda4094",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":627,
                  "y":280},
                "size":{
                  "width":163,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05ff8335b37c4175a8095a7085f2247d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":425},
            "size":{
              "width":129,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18bcfc32b11a40a08ab0cea92ce29771",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":425},
                "size":{
                  "width":129,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c3a12c26dcc467a96bab6e4fbbfedbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":425},
            "size":{
              "width":97,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"daecda73a51f423896dc8d95a3fa7a5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":760,
                  "y":425},
                "size":{
                  "width":97,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bdf164084bf649ff8c32011baaf8528e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1007,
              "y":425},
            "size":{
              "width":81,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f188c4fcebd94bc28ff553558b3273ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1007,
                  "y":425},
                "size":{
                  "width":81,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1df5535f4ecb427687b11b68ca58850b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":390},
            "size":{
              "width":690,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人信息/u36_line.png"}},
{
          "id":"f2ea529d622649019641618224efdb0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":526},
            "size":{
              "width":129,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f0400a09f2142219a44c5a13a2b2b27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":526},
                "size":{
                  "width":129,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"615747c7112d4b1aa4106b3e825e691c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":290,
              "y":533},
            "size":{
              "width":140,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5c357a62bf44b44ae82c0c3de568299",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":290,
                  "y":533},
                "size":{
                  "width":140,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/其他人信息/u33.png"}},
{
          "id":"22b3ba100f4342c1a933ff2dbdffee32",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":1464,
              "y":240},
            "size":{
              "width":140,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fffa83387cb4ba7aa72f039c96cd6dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":1464,
                  "y":240},
                "size":{
                  "width":140,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/其他人信息/u33.png"}},
{
          "id":"845c9ff8c2494020b307fc6ac21fd740",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1464,
              "y":352.5},
            "size":{
              "width":479,
              "height":219}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfe4143a73bb43a5b1125ddc2ddf8268",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1464,
                  "y":352.5},
                "size":{
                  "width":479,
                  "height":219}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/其他人信息/u37.png"}},
{
          "id":"d323d2019bd147b78815bee2ec5e7ba2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":1631,
              "y":240},
            "size":{
              "width":313,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e6b7e50720248f7b59b17a449813465",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1631,
                  "y":240},
                "size":{
                  "width":313,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "4d2967f150dc46348e63af60533b1274":{
      "scriptId":"u0"},
    "5988c005f8aa4cacb62f5ac9ba02970a":{
      "scriptId":"u1"},
    "93f6493fd426410c9776ef676585e533":{
      "scriptId":"u2"},
    "3cf20651accd450e899bd97e7410f9bc":{
      "scriptId":"u3"},
    "65fd10123c8144aca80377f4b52d82eb":{
      "scriptId":"u4"},
    "f4ca6734f54c4b1d8e40b366891c7e30":{
      "scriptId":"u5"},
    "0a3f6c1179c2479e9cce6d9075ce8b08":{
      "scriptId":"u6"},
    "4793c9a5f9d34484980d9c5cbba1740b":{
      "scriptId":"u7"},
    "7a6cab7211d74f2da131d9385fea1890":{
      "scriptId":"u8"},
    "0dbe31df767b4007bd65b0831dda0063":{
      "scriptId":"u9"},
    "821dbe57ab3c431c827a23f936f6449a":{
      "scriptId":"u10"},
    "8f1b5efd72614362ae3f8ebb899f78c2":{
      "scriptId":"u11"},
    "71682685009a476380daa2775c8ec6fc":{
      "scriptId":"u12"},
    "c96d895603b74d149a7436d81151813f":{
      "scriptId":"u13"},
    "51a3e67f78b84beb96b6bbf8a542c267":{
      "scriptId":"u14"},
    "0c4722e86f50447f88ca66981e15c957":{
      "scriptId":"u15"},
    "af5b6ce8f5a8457e86720203d07c4e4b":{
      "scriptId":"u16"},
    "327f1a7b6104479dad3d0c1813ae050d":{
      "scriptId":"u17"},
    "40c4ca5325134addb98283b35a171ba6":{
      "scriptId":"u18"},
    "dce0c53f6ac84ed18b474a0a4a67fd22":{
      "scriptId":"u19"},
    "cdbc32624aab4f12a5d51d83ecc9ca79":{
      "scriptId":"u20"},
    "baa576e8da99470abdfbfc761b25c647":{
      "scriptId":"u21"},
    "25ec5397e12849b5b2fcea6dc3324cc4":{
      "scriptId":"u22"},
    "787ad039a95144eca3bc7821ccda4094":{
      "scriptId":"u23"},
    "05ff8335b37c4175a8095a7085f2247d":{
      "scriptId":"u24"},
    "18bcfc32b11a40a08ab0cea92ce29771":{
      "scriptId":"u25"},
    "1c3a12c26dcc467a96bab6e4fbbfedbe":{
      "scriptId":"u26"},
    "daecda73a51f423896dc8d95a3fa7a5c":{
      "scriptId":"u27"},
    "bdf164084bf649ff8c32011baaf8528e":{
      "scriptId":"u28"},
    "f188c4fcebd94bc28ff553558b3273ec":{
      "scriptId":"u29"},
    "1df5535f4ecb427687b11b68ca58850b":{
      "scriptId":"u30"},
    "f2ea529d622649019641618224efdb0f":{
      "scriptId":"u31"},
    "4f0400a09f2142219a44c5a13a2b2b27":{
      "scriptId":"u32"},
    "615747c7112d4b1aa4106b3e825e691c":{
      "scriptId":"u33"},
    "a5c357a62bf44b44ae82c0c3de568299":{
      "scriptId":"u34"},
    "22b3ba100f4342c1a933ff2dbdffee32":{
      "scriptId":"u35"},
    "0fffa83387cb4ba7aa72f039c96cd6dc":{
      "scriptId":"u36"},
    "845c9ff8c2494020b307fc6ac21fd740":{
      "scriptId":"u37"},
    "dfe4143a73bb43a5b1125ddc2ddf8268":{
      "scriptId":"u38"},
    "d323d2019bd147b78815bee2ec5e7ba2":{
      "scriptId":"u39"},
    "1e6b7e50720248f7b59b17a449813465":{
      "scriptId":"u40"}}});