$axure.loadCurrentPage({
  "url":"弹窗.html",
  "generationDate":new Date(1486804101974.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cb9f39e18c834f5aaefd789624dd083b",
    "type":"Axure:Page",
    "name":"弹窗",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0aa91ec77b504be69935ccb61428374a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":13},
            "size":{
              "width":417,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bf3291abc9b4e1ead103b8c7764cc02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":13},
                "size":{
                  "width":417,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1549913ad48b4a6986b17999adb1d8d6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":97},
            "size":{
              "width":882,
              "height":541}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"679d63c9f80e4c80a24938faa691b303",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":97},
                "size":{
                  "width":882,
                  "height":541}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/弹窗/u2.jpg"}},
{
          "id":"1f02f8366f3f4377b4718d559c9aa0b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":1331},
            "size":{
              "width":545,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5bd769dc244424c9e08aacd515b720d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":1331},
                "size":{
                  "width":545,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"edd1b98632294836ba1a13df72949e8a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":1411},
            "size":{
              "width":483,
              "height":229}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa4722501852473d9cafd76cdf45eb91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":1411},
                "size":{
                  "width":483,
                  "height":229}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/弹窗/u6.png"}},
{
          "id":"f425b85b896a43f8bc1b60f7a576f1ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":735},
            "size":{
              "width":862,
              "height":565}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07031588fc194f92ae53a203f979b94e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":735},
                "size":{
                  "width":862,
                  "height":565}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/弹窗/u8.jpg"}},
{
          "id":"fc2ea36094ed4c34ad63f1754df943c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":670},
            "size":{
              "width":289,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a877de96578241be9c1327c98a92c460",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":670},
                "size":{
                  "width":289,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "0aa91ec77b504be69935ccb61428374a":{
      "scriptId":"u0"},
    "7bf3291abc9b4e1ead103b8c7764cc02":{
      "scriptId":"u1"},
    "1549913ad48b4a6986b17999adb1d8d6":{
      "scriptId":"u2"},
    "679d63c9f80e4c80a24938faa691b303":{
      "scriptId":"u3"},
    "1f02f8366f3f4377b4718d559c9aa0b1":{
      "scriptId":"u4"},
    "c5bd769dc244424c9e08aacd515b720d":{
      "scriptId":"u5"},
    "edd1b98632294836ba1a13df72949e8a":{
      "scriptId":"u6"},
    "aa4722501852473d9cafd76cdf45eb91":{
      "scriptId":"u7"},
    "f425b85b896a43f8bc1b60f7a576f1ef":{
      "scriptId":"u8"},
    "07031588fc194f92ae53a203f979b94e":{
      "scriptId":"u9"},
    "fc2ea36094ed4c34ad63f1754df943c0":{
      "scriptId":"u10"},
    "a877de96578241be9c1327c98a92c460":{
      "scriptId":"u11"}}});