$axure.loadCurrentPage({
  "url":"获得界面.html",
  "generationDate":new Date(1486804102339.12),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4a02a5a96b864a59a66d9fe63c1c5d19",
    "type":"Axure:Page",
    "name":"获得界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"64bc7b3de9dd4d9d86b147c6cf349b87",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":20},
            "size":{
              "width":603,
              "height":350}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"414da2a3bd7e4b1492e4b5a6f1aa447c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":20},
                "size":{
                  "width":603,
                  "height":350}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/获得界面/u0.jpg"}},
{
          "id":"71b66153ae5745fe8f00776e1f2fb491",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":60},
            "size":{
              "width":353,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8140f8c24cc94303a846bef39f02888b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":60},
                "size":{
                  "width":353,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c1c4b197cda45acb371ae0b895f6dc2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":120},
            "size":{
              "width":120,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48434a3bc2934be2810ac89b7d398dce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":120},
                "size":{
                  "width":120,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/获得界面/u4.png"}},
{
          "id":"0d8be462fe5745e8920e682f3048b91a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":193},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db74ca12848f4f21a209717474d82fad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":193},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21cafff3c3df4b21927d1975a0f63bf5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":677,
              "y":240},
            "size":{
              "width":103,
              "height":143}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bacfadc6ba6045af9876006bb9504968",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":677,
                  "y":240},
                "size":{
                  "width":103,
                  "height":143}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/获得界面/u8.png"}},
{
          "id":"c4e8f9c65b5c48b197489af927de31f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":293},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92ba8372c4034313ac1bd296b399fc6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":293},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e26ec01a30448a695b0ebb37404d358",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":677,
              "y":393},
            "size":{
              "width":143,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dadc3d87c9e24a2b9e343012c422f89a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":677,
                  "y":393},
                "size":{
                  "width":143,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/获得界面/u12.png"}},
{
          "id":"68f3182a96d2465e832a3ddfca736359",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":399},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b67a46b602ec4998a5ca38180d2dc535",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":830,
                  "y":399},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "64bc7b3de9dd4d9d86b147c6cf349b87":{
      "scriptId":"u0"},
    "414da2a3bd7e4b1492e4b5a6f1aa447c":{
      "scriptId":"u1"},
    "71b66153ae5745fe8f00776e1f2fb491":{
      "scriptId":"u2"},
    "8140f8c24cc94303a846bef39f02888b":{
      "scriptId":"u3"},
    "1c1c4b197cda45acb371ae0b895f6dc2":{
      "scriptId":"u4"},
    "48434a3bc2934be2810ac89b7d398dce":{
      "scriptId":"u5"},
    "0d8be462fe5745e8920e682f3048b91a":{
      "scriptId":"u6"},
    "db74ca12848f4f21a209717474d82fad":{
      "scriptId":"u7"},
    "21cafff3c3df4b21927d1975a0f63bf5":{
      "scriptId":"u8"},
    "bacfadc6ba6045af9876006bb9504968":{
      "scriptId":"u9"},
    "c4e8f9c65b5c48b197489af927de31f7":{
      "scriptId":"u10"},
    "92ba8372c4034313ac1bd296b399fc6e":{
      "scriptId":"u11"},
    "2e26ec01a30448a695b0ebb37404d358":{
      "scriptId":"u12"},
    "dadc3d87c9e24a2b9e343012c422f89a":{
      "scriptId":"u13"},
    "68f3182a96d2465e832a3ddfca736359":{
      "scriptId":"u14"},
    "b67a46b602ec4998a5ca38180d2dc535":{
      "scriptId":"u15"}}});